"""Default strategy: point the compose service at a branch database.

The strategy writes a minimal override file (gitignored) that replaces the
service `command` with `odoo -d <db> --db-filter=^<db>$` and brings the
service back up. In Docker Compose, `command` in an override REPLACES the
base command - which is exactly what we want, with one consequence: the
base compose service command must be plain `odoo` (extra flags there would
be lost when switching databases).

No `volumes` block is emitted: the override stays minimal (command only).
The seeds folder is mounted by the seeding channel itself via an explicit
`-v`, so seeding does not depend on the override existing yet.
"""

from __future__ import annotations

import re
from pathlib import Path

from dbctl.config import Config
from dbctl.docker import compose
from dbctl.strategies.base import Strategy

_HEADER = "# GENERATED BY dbctl - DO NOT EDIT"


def _command_block(service: str, db: str) -> str:
    return (
        "services:\n"
        f"  {service}:\n"
        f'    command: ["odoo", "-d", "{db}", "--db-filter=^{db}$"]\n'
    )


class ComposeOverrideStrategy(Strategy):
    def __init__(self, cfg: Config) -> None:
        super().__init__(cfg)
        self.override_path: Path = cfg.project_root / cfg.strategy.override_file

    # -- helpers ----------------------------------------------------------
    def _write_override(self, db: str) -> None:
        self.override_path.write_text(
            f"{_HEADER}\n{_command_block(self.cfg.odoo.compose_service, db)}"
        )

    def _compose(self, args: list[str], **kwargs) -> str:
        return compose(self.cfg.project_root, self.cfg.compose_files, args, **kwargs)

    # -- Strategy API -----------------------------------------------------
    def start(self, db: str | None) -> None:
        if db is None:
            self.override_path.unlink(missing_ok=True)
            files = [self.cfg.odoo.compose_file]
        else:
            self._write_override(db)
            files = [self.cfg.odoo.compose_file, self.cfg.strategy.override_file]
        compose(
            self.cfg.project_root,
            files,
            ["up", "-d", self.cfg.odoo.compose_service],
        )

    def stop(self) -> None:
        self._compose(["stop", self.cfg.odoo.compose_service])

    def upgrade(self, db: str, modules: list[str]) -> None:
        self.stop()
        self._compose(
            [
                "run",
                "--rm",
                "--no-deps",
                self.cfg.odoo.compose_service,
                "odoo",
                "-d",
                db,
                "-u",
                ",".join(modules),
                "--stop-after-init",
            ]
        )
        self.start(db)

    def current_database(self) -> str | None:
        if not self.override_path.is_file():
            return None
        text = self.override_path.read_text()
        match = re.search(r'"-d",\s*"([^"]+)"', text)
        return match.group(1) if match else None

    def unuse(self) -> None:
        self.override_path.unlink(missing_ok=True)
