"""dbctl hook - install/remove/run the post-checkout git hook.

The hook keeps the Odoo service serving the right database on every branch
switch (Case 3.1). Same contract as the other commands: returns data, never
prints.

Golden rule: the generated post-checkout must NEVER make `git checkout`
fail. Every error path - missing config, docker down, missing database,
detached HEAD - ends in a `dbctl:` warning line and exit code 0.
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

from dbctl import logging as dlog
from dbctl.commands import use
from dbctl.config import Config
from dbctl.errors import DbctlError, GitError
from dbctl.naming import database_name
from dbctl.postgres import database_exists
from dbctl.project import current_branch, hooks_dir
from dbctl.strategies import get_strategy

SCRIPT_NAME = "post-checkout"
MARKER = "# GENERATED BY dbctl - DO NOT EDIT"


def _hook_path(cfg: Config) -> Path:
    return hooks_dir(cfg.project_root) / SCRIPT_NAME


def _exec_line(cfg: Config) -> str:
    """The single command the generated hook runs (spec section 6)."""
    return (
        f'exec "{sys.executable}" -m dbctl --config "{cfg.path}" hook post-checkout "$1" "$2" "$3"'
    )


def _is_ours(path: Path) -> bool:
    try:
        return MARKER in path.read_text()
    except OSError:
        return False


def _script(cfg: Config) -> str:
    return f"#!/bin/sh\n{MARKER} (dbctl hook install)\n{_exec_line(cfg)}\n"


def install(cfg: Config, *, force: bool = False) -> dict:
    """Write the post-checkout hook (chmod 0755)."""
    path = _hook_path(cfg)
    existed = path.exists()
    ours = existed and _is_ours(path)

    if existed and not ours and not force:
        raise DbctlError(
            f"post-checkout already exists and was not generated by dbctl: {path}\n"
            "To keep it, append this line to it manually:\n"
            f"  {_exec_line(cfg)}\n"
            "Or run 'dbctl hook install --force' to back it up as "
            "post-checkout.bak and overwrite it."
        )

    if os.environ.get("DBCTL_DRY_RUN") == "1":
        action = "updated" if ours else ("forced" if existed else "installed")
        return {"action": f"dry-run: would {action}", "path": str(path)}

    path.parent.mkdir(parents=True, exist_ok=True)
    backup: str | None = None
    if existed and not ours and force:
        backup = str(path.with_name("post-checkout.bak"))
        shutil.copy2(path, backup)
    path.write_text(_script(cfg))
    path.chmod(0o755)
    action = "updated" if ours else ("forced" if existed else "installed")
    return {"action": action, "path": str(path), "backup": backup}


def uninstall(cfg: Config) -> dict:
    """Remove the hook ONLY if dbctl generated it. Never touches third-party."""
    path = _hook_path(cfg)
    if not path.exists():
        return {"action": "absent", "path": str(path)}
    if not _is_ours(path):
        return {"action": "kept", "path": str(path)}
    if os.environ.get("DBCTL_DRY_RUN") == "1":
        return {"action": "dry-run: would remove", "path": str(path)}
    path.unlink()
    return {"action": "removed", "path": str(path)}


def info(cfg: Config) -> dict:
    path = _hook_path(cfg)
    installed = path.exists()
    return {
        "path": str(path),
        "installed": installed,
        "ours": installed and _is_ours(path),
        "enabled": cfg.hooks.enabled,
    }


def on_checkout(cfg: Config, prev: str, new: str, branch_flag: str) -> list[str]:
    """Logic run by the hidden `dbctl hook post-checkout` command.

    Decision order (spec section 6):
      1. branch_flag != "1" -> nothing (file checkout);
      2. hooks.enabled false -> nothing (user's choice);
      3. detached HEAD -> warning, no database resolution;
      4. already serving the target -> "already serving <db>";
      5. target database missing -> warning suggesting `dbctl create --use`;
      6. otherwise delegate to commands/use (never reimplement the override).

    NEVER raises: internal exceptions become `dbctl:` warning lines in the
    returned list. The CLI guarantees exit 0 on top of that.
    """
    messages: list[str] = []
    try:
        dlog.info(
            "hook_checkout",
            prev=prev,
            new=new,
            branch_flag=branch_flag,
            enabled=cfg.hooks.enabled,
        )
        if branch_flag != "1":
            dlog.debug("hook_skipped", reason="file checkout (branch_flag=0)")
            return messages
        if not cfg.hooks.enabled:
            dlog.debug("hook_skipped", reason="hooks disabled")
            return messages

        try:
            branch = current_branch(cfg.project_root)
        except GitError:
            dlog.warning(
                "hook_detached",
                reason="detached HEAD - leaving the current database as is",
            )
            messages.append(
                "dbctl: detached HEAD - leaving the current database as is (rebase/bisect?)"
            )
            return messages

        target = database_name(branch, cfg.postgres.db_prefix)
        strategy = get_strategy(cfg)
        if strategy.current_database() == target:
            dlog.debug("hook_served", db=target, reason="already serving")
            messages.append(f"dbctl: already serving {target}")
            return messages
        if not database_exists(cfg, target):
            dlog.warning(
                "hook_db_missing",
                db=target,
                reason="run 'dbctl create --use' when ready",
            )
            messages.append(
                f"dbctl: database {target} does not exist yet - run 'dbctl create --use' when ready"
            )
            return messages
        use.run(cfg)
        dlog.info("hook_serving", db=target)
        messages.append(f"dbctl: serving {target}")
    except Exception as exc:  # golden rule: never break the checkout
        dlog.error("hook_failed", error_type=type(exc).__name__, message=str(exc))
        messages.append(f"dbctl: hook failed: {exc}")
    return messages
