"""Unit tests for the strategy layer (compose-override + custom)."""

from __future__ import annotations

import pytest

from dbctl.errors import ConfigError
from dbctl.strategies import get_strategy
from dbctl.strategies.compose_override import ComposeOverrideStrategy
from dbctl.strategies.custom import CustomStrategy

# --- compose-override -------------------------------------------------------


def test_override_written_with_command_and_filter(make_config, tmp_path, fake_compose) -> None:
    cfg = make_config()
    strategy = ComposeOverrideStrategy(cfg)
    strategy.start("dev_x")
    override = tmp_path / "docker-compose.override.yaml"
    text = override.read_text(encoding="utf-8")
    assert "# GENERATED BY dbctl - DO NOT EDIT" in text
    assert 'command: ["odoo", "-d", "dev_x", "--db-filter=^dev_x$"]' in text
    # override must be listed AFTER the base file in the compose invocation
    assert fake_compose.last()[:5] == [
        "docker-compose.yml",
        "docker-compose.override.yaml",
        "up",
        "-d",
        "web",
    ] or fake_compose.last()[:2] == ["docker-compose.yml", "docker-compose.override.yaml"]


def test_start_none_removes_override_and_uses_base_only(
    make_config, tmp_path, fake_compose
) -> None:
    cfg = make_config()
    strategy = ComposeOverrideStrategy(cfg)
    override = tmp_path / "docker-compose.override.yaml"
    override.write_text("old", encoding="utf-8")
    strategy.start(None)
    assert not override.exists()
    assert fake_compose.last()[:1] == ["docker-compose.yml"]


def test_stop(make_config, fake_compose) -> None:
    ComposeOverrideStrategy(make_config()).stop()
    assert fake_compose.last()[:2] == ["stop", "web"] or "stop" in fake_compose.last()


def test_apply_schema_builds_u_and_i_flags(make_config, fake_compose) -> None:
    ComposeOverrideStrategy(make_config()).apply_schema("dev_x", ["a", "b"], ["c"])
    cmd = fake_compose.last()
    joined = " ".join(cmd)
    assert "-u" in joined and "a,b" in joined
    assert "-i" in joined and "c" in joined
    assert "--stop-after-init" in joined
    assert "run" in joined and "--no-deps" in joined


def test_apply_schema_omits_empty_flags(make_config, fake_compose) -> None:
    ComposeOverrideStrategy(make_config()).apply_schema("dev_x", [])
    tokens = fake_compose.last()
    assert "-u" not in tokens and "-i" not in tokens
    assert "--stop-after-init" in tokens


def test_upgrade_stop_then_schema_then_start(make_config, fake_compose) -> None:
    ComposeOverrideStrategy(make_config()).upgrade("dev_x", ["m"])
    flat = " | ".join(" ".join(c) for c in fake_compose.calls)
    assert flat.index("stop") < flat.index("--stop-after-init") < flat.index(" up ")


def test_upgrade_order_indexes(make_config, fake_compose) -> None:
    ComposeOverrideStrategy(make_config()).upgrade("dev_x", ["m"])
    stops = [i for i, c in enumerate(fake_compose.calls) if "stop" in c]
    runs = [i for i, c in enumerate(fake_compose.calls) if "--stop-after-init" in c]
    ups = [i for i, c in enumerate(fake_compose.calls) if "up" in c]
    assert stops and runs and ups
    assert stops[0] < runs[0] < ups[0]


def test_current_database_reads_override(make_config, tmp_path) -> None:
    strategy = ComposeOverrideStrategy(make_config())
    assert strategy.current_database() is None
    override = (
        "# GENERATED BY dbctl - DO NOT EDIT\n"
        "services:\n  web:\n"
        '    command: ["odoo", "-d", "dev_abc", "--db-filter=^dev_abc$"]\n'
    )
    (tmp_path / "docker-compose.override.yaml").write_text(override, encoding="utf-8")
    assert strategy.current_database() == "dev_abc"


def test_unuse_removes_override(make_config, tmp_path) -> None:
    (tmp_path / "docker-compose.override.yaml").write_text("x", encoding="utf-8")
    strategy = ComposeOverrideStrategy(make_config())
    strategy.unuse()
    assert not (tmp_path / "docker-compose.override.yaml").exists()


# --- custom -----------------------------------------------------------------


def test_custom_strategy_requires_upgrade_for_apply_schema(make_config, monkeypatch) -> None:
    monkeypatch.setenv("DBCTL_STRATEGY_KIND", "custom")
    monkeypatch.setenv("DBCTL_STRATEGY_COMMANDS_START", "./run.sh start")
    monkeypatch.setenv("DBCTL_STRATEGY_COMMANDS_STOP", "./run.sh stop")
    cfg = make_config()
    strategy = CustomStrategy(cfg)
    with pytest.raises(ConfigError, match="upgrade"):
        strategy.apply_schema("dev_x", ["m"])


def test_custom_strategy_placeholders(make_config, monkeypatch) -> None:
    calls: list[list[str]] = []
    monkeypatch.setattr(
        "dbctl.strategies.custom.run",
        lambda args, **kw: calls.append(args),
    )
    monkeypatch.setenv("DBCTL_STRATEGY_KIND", "custom")
    monkeypatch.setenv("DBCTL_STRATEGY_COMMANDS_START", "start {db}")
    monkeypatch.setenv("DBCTL_STRATEGY_COMMANDS_STOP", "stop")
    monkeypatch.setenv(
        "DBCTL_STRATEGY_COMMANDS_UPGRADE",
        "upgrade {db} {modules} {install} {project_root}",
    )
    cfg = make_config()
    strategy = CustomStrategy(cfg)
    strategy.start("dev_x")
    assert calls[-1] == ["bash", "-c", "start dev_x"]
    strategy.apply_schema("dev_x", ["a", "b"], ["c"])
    filled = calls[-1][-1]
    assert filled.startswith("upgrade dev_x a,b c ")
    assert str(cfg.project_root) in filled


def test_custom_current_database_is_none(make_config, monkeypatch) -> None:
    monkeypatch.setenv("DBCTL_STRATEGY_KIND", "custom")
    monkeypatch.setenv("DBCTL_STRATEGY_COMMANDS_START", "true")
    monkeypatch.setenv("DBCTL_STRATEGY_COMMANDS_STOP", "true")
    assert CustomStrategy(make_config()).current_database() is None


def test_get_strategy_selects_kind(make_config) -> None:
    assert isinstance(get_strategy(make_config()), ComposeOverrideStrategy)
