"""Unit tests for the post-checkout hook lifecycle (commands/hook)."""

from __future__ import annotations

import pytest

from dbctl.commands import hook as hook_cmd
from dbctl.errors import DbctlError


def _cfg_for(git_repo, make_config):
    return make_config(root=git_repo)


def test_install_writes_executable_hook(git_repo, make_config) -> None:
    cfg = _cfg_for(git_repo, make_config)
    result = hook_cmd.install(cfg)
    path = cfg.project_root / ".git" / "hooks" / "post-checkout"
    assert result["action"] == "installed"
    assert path.exists()
    assert path.stat().st_mode & 0o111
    text = path.read_text(encoding="utf-8")
    assert "# GENERATED BY dbctl - DO NOT EDIT" in text
    assert 'hook post-checkout "$1" "$2" "$3"' in text
    assert str(cfg.path) in text


def test_install_updates_own_hook(git_repo, make_config) -> None:
    cfg = _cfg_for(git_repo, make_config)
    hook_cmd.install(cfg)
    result = hook_cmd.install(cfg)
    assert result["action"] == "updated"


def test_install_refuses_third_party_without_force(git_repo, make_config) -> None:
    cfg = _cfg_for(git_repo, make_config)
    path = cfg.project_root / ".git" / "hooks" / "post-checkout"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("#!/bin/sh\n# mine\n", encoding="utf-8")
    with pytest.raises(DbctlError, match="not generated by dbctl"):
        hook_cmd.install(cfg)


def test_install_force_backs_up(git_repo, make_config) -> None:
    cfg = _cfg_for(git_repo, make_config)
    path = cfg.project_root / ".git" / "hooks" / "post-checkout"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("#!/bin/sh\n# mine\n", encoding="utf-8")
    result = hook_cmd.install(cfg, force=True)
    assert result["action"] == "forced"
    assert result["backup"] and (cfg.project_root / ".git" / "hooks" / "post-checkout.bak").exists()


def test_uninstall_removes_only_ours(git_repo, make_config) -> None:
    cfg = _cfg_for(git_repo, make_config)
    path = cfg.project_root / ".git" / "hooks" / "post-checkout"
    assert hook_cmd.uninstall(cfg)["action"] == "absent"
    hook_cmd.install(cfg)
    assert hook_cmd.uninstall(cfg)["action"] == "removed"
    assert not path.exists()


def test_uninstall_keeps_third_party(git_repo, make_config) -> None:
    cfg = _cfg_for(git_repo, make_config)
    path = cfg.project_root / ".git" / "hooks" / "post-checkout"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("#!/bin/sh\n# mine\n", encoding="utf-8")
    assert hook_cmd.uninstall(cfg)["action"] == "kept"
    assert path.exists()


def test_info(git_repo, make_config) -> None:
    cfg = _cfg_for(git_repo, make_config)
    info = hook_cmd.info(cfg)
    assert info["installed"] is False
    assert info["ours"] is False
    hook_cmd.install(cfg)
    info = hook_cmd.info(cfg)
    assert info["installed"] is True
    assert info["ours"] is True
    assert info["enabled"] is True


# --- on_checkout decision table ---------------------------------------------


def test_on_checkout_file_checkout_skips(git_repo, make_config, monkeypatch) -> None:
    cfg = _cfg_for(git_repo, make_config)
    called: list[str] = []
    monkeypatch.setattr("dbctl.commands.hook.use.run", lambda c: called.append("use"))
    assert hook_cmd.on_checkout(cfg, "main", "feature", "0") == []
    assert called == []


def test_on_checkout_hooks_disabled_skips(git_repo, make_config, monkeypatch) -> None:
    cfg = _cfg_for(git_repo, make_config)
    cfg.hooks.enabled = False
    called: list[str] = []
    monkeypatch.setattr("dbctl.commands.hook.use.run", lambda c: called.append("use"))
    assert hook_cmd.on_checkout(cfg, "main", "feature", "1") == []
    assert called == []


def test_on_checkout_detached_warns(git_repo, make_config, monkeypatch) -> None:
    cfg = _cfg_for(git_repo, make_config)
    import subprocess

    subprocess.run(["git", "-C", str(git_repo), "checkout", "-q", "--detach"], check=True)
    messages = hook_cmd.on_checkout(cfg, "main", "HEAD", "1")
    assert any("detached HEAD" in m for m in messages)


def test_on_checkout_missing_db_warns(git_repo, make_config, monkeypatch) -> None:
    cfg = _cfg_for(git_repo, make_config)
    monkeypatch.setattr("dbctl.commands.hook.database_exists", lambda c, db: False)
    messages = hook_cmd.on_checkout(cfg, "main", "feature", "1")
    assert any("does not exist yet" in m for m in messages)


def test_on_checkout_already_serving(git_repo, make_config, monkeypatch) -> None:
    cfg = _cfg_for(git_repo, make_config)
    monkeypatch.setattr("dbctl.commands.hook.database_exists", lambda c, db: True)
    strategy = hook_cmd.get_strategy(cfg)
    monkeypatch.setattr("dbctl.commands.hook.get_strategy", lambda c: strategy)
    from dbctl.naming import database_name

    target = database_name("feature", cfg.postgres.db_prefix)
    strategy.current_database = lambda: target  # type: ignore[method-assign]
    messages = hook_cmd.on_checkout(cfg, "main", "feature", "1")
    assert any("already serving" in m for m in messages)


def test_on_checkout_delegates_to_use(git_repo, make_config, monkeypatch) -> None:
    cfg = _cfg_for(git_repo, make_config)
    monkeypatch.setattr("dbctl.commands.hook.database_exists", lambda c, db: True)
    strategy = hook_cmd.get_strategy(cfg)
    monkeypatch.setattr("dbctl.commands.hook.get_strategy", lambda c: strategy)
    strategy.current_database = lambda: None  # type: ignore[method-assign]
    used: list[str] = []
    monkeypatch.setattr("dbctl.commands.hook.use.run", lambda c: used.append("use"))
    messages = hook_cmd.on_checkout(cfg, "main", "feature", "1")
    assert used == ["use"]
    assert any("serving" in m for m in messages)


def _cfg_clean(git_repo, tmp_path, make_config):
    """Config file outside the repo: the working tree stays really clean."""
    return make_config(root=git_repo, config=tmp_path / "cfg.toml")


# --- stash automático de working tree sujo -----------------------------------


def test_on_checkout_stashes_dirty_tree(git_repo, make_config, tmp_path, monkeypatch) -> None:
    cfg = _cfg_clean(git_repo, tmp_path, make_config)
    monkeypatch.setattr("dbctl.commands.hook.database_exists", lambda c, db: False)
    (git_repo / "wip.txt").write_text("work in progress\n", encoding="utf-8")
    (git_repo / "untracked.txt").write_text("new file\n", encoding="utf-8")

    messages = hook_cmd.on_checkout(cfg, "main", "feature", "1")

    assert any("stash" in m and "dbctl-wip main" in m for m in messages)
    # The changes really are parked in a named, recoverable stash.
    import subprocess

    listing = subprocess.run(
        ["git", "-C", str(git_repo), "stash", "list"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    assert "dbctl-wip main" in listing
    # And the working tree is clean again (the new branch DB matches the code):
    # the untracked wip.txt went into the stash too (-u flag).
    assert not (git_repo / "wip.txt").exists()


def test_on_checkout_clean_tree_no_stash(git_repo, make_config, tmp_path, monkeypatch) -> None:
    cfg = _cfg_clean(git_repo, tmp_path, make_config)
    monkeypatch.setattr("dbctl.commands.hook.database_exists", lambda c, db: False)
    messages = hook_cmd.on_checkout(cfg, "main", "feature", "1")
    assert not any("stash" in m for m in messages)


def test_on_checkout_stash_disabled_keeps_tree(
    git_repo, make_config, tmp_path, monkeypatch
) -> None:
    cfg = _cfg_clean(git_repo, tmp_path, make_config)
    cfg.hooks.stash_dirty = False
    monkeypatch.setattr("dbctl.commands.hook.database_exists", lambda c, db: False)
    (git_repo / "wip.txt").write_text("work in progress\n", encoding="utf-8")
    messages = hook_cmd.on_checkout(cfg, "main", "feature", "1")
    assert not any("stash" in m for m in messages)
    assert (git_repo / "wip.txt").exists()  # changes left alone


def test_on_checkout_stash_failure_never_breaks(
    git_repo, make_config, tmp_path, monkeypatch
) -> None:
    cfg = _cfg_clean(git_repo, tmp_path, make_config)
    monkeypatch.setattr("dbctl.commands.hook.database_exists", lambda c, db: False)
    (git_repo / "wip.txt").write_text("work in progress\n", encoding="utf-8")

    from dbctl.errors import DockerError

    def boom(*args, **kwargs):  # noqa: ANN001, ANN202
        raise DockerError("git exploded")

    monkeypatch.setattr("dbctl.commands.hook.run", boom)
    # The stash step fails, but the checkout keeps going (golden rule).
    messages = hook_cmd.on_checkout(cfg, "main", "feature", "1")
    assert any("não consegui guardar" in m for m in messages)


def test_on_checkout_detached_skips_stash(git_repo, make_config, tmp_path, monkeypatch) -> None:
    cfg = _cfg_clean(git_repo, tmp_path, make_config)
    monkeypatch.setattr("dbctl.commands.hook.database_exists", lambda c, db: False)
    (git_repo / "wip.txt").write_text("work in progress\n", encoding="utf-8")
    import subprocess

    subprocess.run(["git", "-C", str(git_repo), "checkout", "-q", "--detach"], check=True)
    messages = hook_cmd.on_checkout(cfg, "main", "HEAD", "1")
    assert any("detached HEAD" in m for m in messages)
    # Rebase/bisect states are never stashed (would corrupt the operation).
    assert not any("stash" in m for m in messages)
