"""Unit tests for command orchestration (commands/*): flows, guards, precedence.

Regression anchors from the spec validation plan:
  V12  re-create refuses ("already exists - use 'dbctl reset'")
  V17  drop of a non-prefixed database is refused (double guard)
  V34  abort without confirmation (UserAbort, exit 130)
  V38  unuse removes the override / V39  create --use serves right away
"""

from __future__ import annotations

import pytest

from dbctl.commands import create, drop, list_dbs, reset, seed, status, unuse, upgrade, use
from dbctl.config import Config
from dbctl.errors import ConfigError, DatabaseError, UserAbort

# --- status -----------------------------------------------------------------


def test_status_shape(make_config, fake_psql, fake_compose, fake_run, monkeypatch) -> None:
    fake_psql.default = ""  # database does not exist
    monkeypatch.setattr("dbctl.commands.status.database_exists", lambda c, db: False)
    monkeypatch.setattr("dbctl.commands.status.working_tree_dirty", lambda r: False)
    info = status.run(make_config())
    assert info["branch"] == "feature-x"
    assert info["target_db"].startswith("dev_")
    assert info["exists"] is False
    assert info["served"] is None
    assert info["template"] == "tpl"
    assert info["hook"]["installed"] is False
    assert info["changed_modules"]["enabled"] is True
    assert info["dirty"] is False


def test_status_detection_error_does_not_raise(
    make_config, fake_psql, fake_run, monkeypatch
) -> None:
    monkeypatch.setattr("dbctl.commands.status.database_exists", lambda c, db: False)

    def boom(cfg):  # noqa: ANN001
        raise ConfigError("no base ref")

    monkeypatch.setattr("dbctl.modules.detect", boom)
    info = status.run(make_config())
    assert info["changed_modules"]["error"] is not None
    assert info["changed_modules"]["modules"] == []


# --- use / unuse -------------------------------------------------------------


def test_use_requires_existing_db(make_config, fake_psql, fake_compose, fake_run) -> None:
    fake_psql.default = ""
    with pytest.raises(DatabaseError, match="does not exist"):
        use.run(make_config())


def test_use_starts_strategy(make_config, fake_psql, fake_compose, fake_run) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    result = use.run(make_config())
    assert result["db"].startswith("dev_")
    assert fake_compose.last()[:2] == ["docker-compose.yml", "docker-compose.override.yaml"]


def test_unuse_removed_true_when_override_exists(make_config, tmp_path) -> None:
    cfg = make_config()
    (tmp_path / "docker-compose.override.yaml").write_text(
        "# GENERATED BY dbctl - DO NOT EDIT\nservices:\n  web:\n"
        '    command: ["odoo", "-d", "dev_x", "--db-filter=^dev_x$"]\n',
        encoding="utf-8",
    )
    result = unuse.run(cfg)
    assert result["removed"] is True
    assert not (tmp_path / "docker-compose.override.yaml").exists()


def test_unuse_removed_false_when_absent(make_config) -> None:
    assert unuse.run(make_config())["removed"] is False


# --- seed -------------------------------------------------------------------


def test_seed_requires_db(make_config, fake_psql, fake_run) -> None:
    fake_psql.default = ""
    with pytest.raises(DatabaseError, match="does not exist"):
        seed.run(make_config())


def test_seed_skipped_when_unconfigured(make_config, fake_psql, fake_run) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    assert seed.run(make_config()) == {"skipped": True}


def test_seed_returns_ran(make_config, fake_psql, tmp_path, fake_run, monkeypatch) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    seeds = tmp_path / "temp" / "seeds"
    seeds.mkdir(parents=True)
    (seeds / "base.py").write_text("x", encoding="utf-8")
    cfg = make_config('[seeds]\npath = "temp/seeds"\n')
    monkeypatch.setattr("dbctl.commands.seed.run_seeds", lambda c, db, br: ["base.py"])
    assert seed.run(cfg) == {"ran": ["base.py"]}


# --- list -------------------------------------------------------------------


def test_list_rows_and_current(make_config, fake_psql, fake_compose, fake_run) -> None:
    fake_psql.on("pg_database_size", returns="dev_a|1 MB\ndev_b|2 MB\n")
    result = list_dbs.run(make_config())
    assert result["rows"] == [("dev_a", "1 MB"), ("dev_b", "2 MB")]
    assert result["current"].startswith("dev_")
    assert result["served"] is None


# --- drop -------------------------------------------------------------------


def test_drop_refuses_outside_prefix(make_config) -> None:
    with pytest.raises(DatabaseError, match="does not start with db_prefix"):
        drop.run(make_config(), db="other_db")


def test_drop_aborts_without_confirmation(make_config) -> None:
    with pytest.raises(UserAbort):
        drop.run(make_config(), db="dev_x", ask=lambda m: False)


def test_drop_confirmed_drops(make_config, fake_psql, fake_compose, monkeypatch) -> None:
    fake_psql.default = ""
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    monkeypatch.setattr("dbctl.commands.drop.filestore_remove", lambda c, db: None)
    result = drop.run(make_config(), db="dev_x", yes=True)
    assert result == {"db": "dev_x", "existed": True}
    drops = [c[-1] for c in fake_psql.calls if "DROP DATABASE" in c[-1]]
    assert drops and 'DROP DATABASE IF EXISTS "dev_x"' in drops[0]


def test_drop_stops_service_when_serving(make_config, fake_psql, fake_compose) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    cfg = make_config()
    # A real override on disk: the strategy's current_database() reads it.
    (cfg.project_root / "docker-compose.override.yaml").write_text(
        "# GENERATED BY dbctl - DO NOT EDIT\nservices:\n  web:\n"
        '    command: ["odoo", "-d", "dev_x", "--db-filter=^dev_x$"]\n',
        encoding="utf-8",
    )
    drop.run(cfg, db="dev_x", yes=True)
    # strategy.stop() -> compose stop, then unuse removes the override
    assert any("stop" in c for c in fake_compose.calls)
    assert not (cfg.project_root / cfg.strategy.override_file).exists()


# --- reset ------------------------------------------------------------------


def test_reset_aborts_without_confirmation(make_config, fake_run) -> None:
    with pytest.raises(UserAbort):
        reset.run(make_config(), ask=lambda m: False)


def test_reset_drops_then_creates(
    make_config, fake_psql, fake_compose, fake_run, monkeypatch
) -> None:
    fake_psql.default = ""
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    monkeypatch.setattr("dbctl.commands.reset.filestore_remove", lambda c, db: None)
    monkeypatch.setattr(
        "dbctl.commands.reset.create.run",
        lambda cfg, use: {"db": "dev_x", "source": "tpl", "seeds": []},
    )
    result = reset.run(make_config(), yes=True)
    assert result["db"].startswith("dev_")
    assert result["source"] == "tpl"
    drops = [c[-1] for c in fake_psql.calls if "DROP DATABASE" in c[-1]]
    assert drops


def test_reset_fresh_confirmation_mentions_scratch(tmp_path, fake_run) -> None:
    from dbctl.commands import reset as reset_cmd

    cfg = _fresh_config(tmp_path)
    messages: list[str] = []
    with pytest.raises(UserAbort):
        reset_cmd.run(cfg, ask=lambda m: messages.append(m) or False)
    assert messages and "scratch (fresh)" in messages[0]
    assert "'None'" not in messages[0]


# --- upgrade precedence -----------------------------------------------------


def test_upgrade_explicit_modules_wins(
    make_config, fake_psql, fake_compose, fake_run, monkeypatch
) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    monkeypatch.setattr("dbctl.modules.detect", lambda cfg: pytest.fail("detect must not run"))
    result = upgrade.run(make_config(), modules=["a", "b"])
    assert result["modules"] == ["a", "b"]
    assert result["detection"] is None
    assert any("-u" in c and "a,b" in c for c in fake_compose.calls)


def test_upgrade_all_flag(make_config, fake_psql, fake_compose, fake_run) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    result = upgrade.run(make_config(), all_modules=True)
    assert result["modules"] == ["all"]


def test_upgrade_all_flag_respects_exclude(
    make_config, fake_psql, fake_compose, fake_run, monkeypatch
) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    monkeypatch.setattr("dbctl.commands.upgrade.installed_modules", lambda cfg, db: {"a", "b", "c"})
    cfg = make_config('[modules]\nexclude = ["b"]\n')
    result = upgrade.run(cfg, all_modules=True)
    # "-u all" cannot itself skip a module, so exclude expands it into an
    # explicit list instead of the literal "all".
    assert result["modules"] == ["a", "c"]
    assert result["excluded"] == ["b"]
    assert any("-u" in c and "a,c" in c for c in fake_compose.calls)


def test_upgrade_all_flag_with_exclude_needs_installed_table(
    make_config, fake_psql, fake_compose, fake_run, monkeypatch
) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    monkeypatch.setattr("dbctl.commands.upgrade.installed_modules", lambda cfg, db: None)
    cfg = make_config('[modules]\nexclude = ["b"]\n')
    with pytest.raises(ConfigError, match="ir_module_module"):
        upgrade.run(cfg, all_modules=True)


def test_upgrade_default_modules_respects_exclude(
    make_config, fake_psql, fake_compose, fake_run
) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    cfg = make_config('default_modules = ["a", "b"]\n[modules]\nexclude = ["b"]\n')
    result = upgrade.run(cfg, detect=False)
    assert result["modules"] == ["a"]
    assert result["excluded"] == ["b"]


def test_upgrade_detect_splits_install_new(
    make_config, fake_psql, fake_compose, fake_run, monkeypatch
) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    monkeypatch.setattr(
        "dbctl.modules.detect",
        lambda cfg: {
            "base_ref": "origin/main",
            "base_sha": "abc123",
            "modules": ["old", "fresh"],
            "changed_paths": ["addons/old/x.py", "addons/fresh/__manifest__.py"],
            "excluded": [],
            "unmatched": [],
        },
    )
    monkeypatch.setattr("dbctl.commands.upgrade.installed_modules", lambda cfg, db: {"old"})
    result = upgrade.run(make_config())
    assert result["modules"] == ["old"]
    assert result["install"] == ["fresh"]
    assert any("-u" in c and "old" in c for c in fake_compose.calls)
    assert any("-i" in c and "fresh" in c for c in fake_compose.calls)


def test_upgrade_nothing_changed_falls_back_to_defaults(
    make_config, fake_psql, fake_compose, fake_run, monkeypatch
) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    monkeypatch.setattr(
        "dbctl.modules.detect",
        lambda cfg: {
            "base_ref": "origin/main",
            "base_sha": "abc",
            "modules": [],
            "changed_paths": [],
            "excluded": [],
            "unmatched": [],
        },
    )
    cfg = make_config('default_modules = ["base"]\n')
    result = upgrade.run(cfg)
    assert result["modules"] == ["base"]


def test_upgrade_nothing_no_defaults_reports(make_config, fake_psql, fake_run, monkeypatch) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    monkeypatch.setattr(
        "dbctl.modules.detect",
        lambda cfg: {
            "base_ref": "origin/main",
            "base_sha": "abc",
            "modules": [],
            "changed_paths": [],
            "excluded": [],
            "unmatched": [],
        },
    )
    result = upgrade.run(make_config())
    assert result["nothing"] is True
    assert result["reason"] == "nothing changed"


def test_upgrade_detect_disabled_without_defaults_raises(make_config, fake_psql, fake_run) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    with pytest.raises(ConfigError, match="no modules to upgrade"):
        upgrade.run(make_config(), detect=False)


def test_upgrade_requires_db(make_config, fake_psql, fake_run) -> None:
    fake_psql.default = ""
    with pytest.raises(DatabaseError, match="does not exist"):
        upgrade.run(make_config())


# --- create -----------------------------------------------------------------


def test_create_refuses_when_db_exists(make_config, fake_psql, fake_compose, fake_run) -> None:
    fake_psql.on("SELECT 1 FROM pg_database", returns="1\n")
    with pytest.raises(DatabaseError, match="already exists"):
        create.run(make_config())


def test_create_requires_template(make_config, fake_psql, fake_compose, fake_run) -> None:
    fake_psql.default = ""  # neither db nor template exist
    with pytest.raises(DatabaseError, match="template database 'tpl' does not exist"):
        create.run(make_config())


def _fresh_config(tmp_path, *, odoo_extra: str = "", extra: str = "") -> Config:  # noqa: ANN001
    """A valid config WITHOUT postgres.template_db (fresh-create mode)."""
    from dbctl.config import load_config

    cfg_path = tmp_path / ".dbctl.toml"
    cfg_path.write_text(
        '[postgres]\ncontainer="c"\nuser="u"\npassword="p"\n'
        '[odoo]\ncontainer="o"\ncompose_service="web"\n' + odoo_extra + extra,
        encoding="utf-8",
    )
    return load_config(tmp_path, cfg_path)


def test_create_fresh_without_template(
    make_config, fake_psql, fake_compose, tmp_path, fake_run, monkeypatch
) -> None:
    seeds = tmp_path / "temp" / "seeds"
    seeds.mkdir(parents=True)
    (seeds / "base.py").write_text("x", encoding="utf-8")
    cfg = _fresh_config(
        tmp_path,
        odoo_extra='default_modules = ["proj_core"]\n',
        extra='[seeds]\npath = "temp/seeds"\n',
    )
    fake_psql.default = ""
    monkeypatch.setattr(
        "dbctl.modules.detect",
        lambda cfg: {
            "base_ref": "origin/main",
            "base_sha": "abc",
            "modules": ["demo"],
            "changed_paths": ["addons/demo/x.py"],
            "excluded": [],
            "unmatched": [],
        },
    )
    sanitize_calls: list[str] = []
    monkeypatch.setattr("dbctl.commands.create.sanitize", lambda c, db: sanitize_calls.append(db))
    fake_compose.on("shell", returns="DBCTL_SEED_RAN:/mnt/dbctl-seeds/base.py\n")

    result = create.run(cfg, use=True)

    assert result["db"].startswith("dev_")
    assert result["source"] is None  # fresh, no template
    assert result["filestore"] == "none"  # nothing to copy
    assert result["seeds"] and result["seeds"][0].endswith("base.py")
    assert result["served"] == result["db"]
    assert sanitize_calls == []  # nothing to sanitize on an empty database

    # empty CREATE DATABASE, no TEMPLATE, no connection juggling
    all_sql = " | ".join(c[-1] for c in fake_psql.calls)
    assert 'CREATE DATABASE "dev_' in all_sql
    assert "TEMPLATE" not in all_sql
    assert "pg_terminate_backend" not in all_sql
    # schema init installs base + defaults + detected module (-i, never -u)
    schema_calls = [c for c in fake_compose.calls if "--stop-after-init" in c]
    assert schema_calls, "fresh create must initialize the schema"
    schema_args = " ".join(schema_calls[0])
    assert "-i" in schema_args and "base,proj_core,demo" in schema_args
    assert "-u" not in schema_args
    # seeds run AFTER the schema init (they need Odoo tables)
    schema_idx = next(i for i, c in enumerate(fake_compose.calls) if "--stop-after-init" in c)
    seed_idx = next(i for i, c in enumerate(fake_compose.calls) if "shell" in c)
    assert schema_idx < seed_idx
    assert any("up" in c for c in fake_compose.calls), "final start missing"


def test_create_fresh_from_override_clones(
    make_config, fake_psql, fake_compose, tmp_path, fake_run, monkeypatch
) -> None:
    # No template in the config, but --from makes the clone optional: on.
    cfg = _fresh_config(tmp_path)
    fake_psql.default = ""
    fake_psql.on("other_tpl", returns="1\n")
    monkeypatch.setattr(
        "dbctl.modules.detect",
        lambda cfg: {
            "base_ref": "origin/main",
            "base_sha": "abc",
            "modules": [],
            "changed_paths": [],
            "excluded": [],
            "unmatched": [],
        },
    )
    fake_compose.on("DBCTL_FILESTORE_MISSING", returns="DBCTL_FILESTORE_MISSING")

    result = create.run(cfg, template="other_tpl")

    assert result["source"] == "other_tpl"
    assert result["filestore"] == "missing"
    all_sql = " | ".join(c[-1] for c in fake_psql.calls)
    assert 'CREATE DATABASE "dev_' in all_sql
    assert 'TEMPLATE "other_tpl"' in all_sql
    assert "pg_terminate_backend" in all_sql  # clone path terminates connections


def test_create_fresh_detect_disabled_still_installs_base(
    make_config, fake_psql, fake_compose, tmp_path, fake_run, monkeypatch
) -> None:
    cfg = _fresh_config(
        tmp_path,
        odoo_extra='default_modules = ["proj_core"]\n',
        extra="[modules]\ndetect = false\n",
    )
    fake_psql.default = ""
    sanitize_calls: list[str] = []
    monkeypatch.setattr("dbctl.commands.create.sanitize", lambda c, db: sanitize_calls.append(db))

    result = create.run(cfg)

    assert result["upgrade"]["install"] == ["base", "proj_core"]
    assert result["upgrade"]["base_sha"] is None
    schema_calls = [c for c in fake_compose.calls if "--stop-after-init" in c]
    assert schema_calls, "fresh create must initialize the schema even without detection"
    assert "base,proj_core" in " ".join(schema_calls[0])
    assert sanitize_calls == []


def test_create_full_flow(
    make_config, fake_psql, fake_compose, tmp_path, fake_run, monkeypatch
) -> None:
    fake_psql.default = ""
    fake_psql.on("tpl", returns="1\n")
    # detection finds nothing changed -> no schema step
    monkeypatch.setattr(
        "dbctl.modules.detect",
        lambda cfg: {
            "base_ref": "origin/main",
            "base_sha": "abc",
            "modules": [],
            "changed_paths": [],
            "excluded": [],
            "unmatched": [],
        },
    )
    seeds = tmp_path / "temp" / "seeds"
    seeds.mkdir(parents=True)
    (seeds / "base.py").write_text("x", encoding="utf-8")
    cfg = make_config('[seeds]\npath = "temp/seeds"\n')
    fake_compose.on("DBCTL_FILESTORE_COPIED", returns="DBCTL_FILESTORE_COPIED")
    fake_compose.on("shell", returns="DBCTL_SEED_RAN:/mnt/dbctl-seeds/base.py\n")

    result = create.run(cfg, use=True)

    assert result["db"].startswith("dev_")
    assert result["source"] == "tpl"
    assert result["filestore"] == "copied"
    assert result["seeds"] and result["seeds"][0].endswith("base.py")
    assert result["served"] == result["db"]

    # phase order: stop -> terminate -> clone -> filestore -> sanitize -> schema -> seeds -> start
    all_sql = " | ".join(c[-1] for c in fake_psql.calls)
    stop_calls = [c for c in fake_compose.calls if "stop" in c]
    assert stop_calls, "strategy.stop must run first (clone needs zero connections)"
    assert "pg_terminate_backend" in all_sql
    assert 'CREATE DATABASE "dev_' in all_sql
    assert any("up" in c for c in fake_compose.calls), "final start missing"
    # override written by the final start
    override = tmp_path / "docker-compose.override.yaml"
    assert override.exists()


def test_create_no_use_restores_previous(
    make_config, fake_psql, fake_compose, tmp_path, fake_run, monkeypatch
) -> None:
    fake_psql.default = ""
    fake_psql.on("tpl", returns="1\n")
    fake_psql.on("dev_prev", returns="1\n")
    monkeypatch.setattr(
        "dbctl.modules.detect",
        lambda cfg: {
            "base_ref": "x",
            "base_sha": "y",
            "modules": [],
            "changed_paths": [],
            "excluded": [],
            "unmatched": [],
        },
    )
    cfg = make_config()
    # The service is currently serving dev_prev (real override on disk).
    (tmp_path / "docker-compose.override.yaml").write_text(
        "# GENERATED BY dbctl - DO NOT EDIT\nservices:\n  web:\n"
        '    command: ["odoo", "-d", "dev_prev", "--db-filter=^dev_prev$"]\n',
        encoding="utf-8",
    )
    fake_compose.on("DBCTL_FILESTORE_MISSING", returns="DBCTL_FILESTORE_MISSING")
    result = create.run(cfg, use=False)
    assert result["served"] == "dev_prev"


def test_create_cleanup_partial_clone(
    make_config, fake_psql, fake_compose, fake_run, monkeypatch
) -> None:
    from dbctl.errors import DatabaseError

    state = {"exists": False}

    def fake_exists(cfg, name):  # noqa: ANN001
        return "tpl" in name or state["exists"]

    def fake_clone(cfg, source, target):  # noqa: ANN001
        state["exists"] = True  # the partial clone appears
        raise DatabaseError("clone exploded")

    monkeypatch.setattr("dbctl.commands.create.database_exists", fake_exists)
    monkeypatch.setattr("dbctl.commands.create.clone_database", fake_clone)
    monkeypatch.setattr(
        "dbctl.commands.create.drop_database", lambda cfg, db: state.__setitem__("dropped", db)
    )
    monkeypatch.setattr("dbctl.sanitize.sanitize", lambda c, db: None)
    monkeypatch.setattr("dbctl.commands.create.run_seeds", lambda c, db, br: [])
    with pytest.raises(DatabaseError):
        create.run(make_config())
    assert state.get("dropped"), "partial clone must be cleaned up"


def test_create_upgrade_applies_schema(
    make_config, fake_psql, fake_compose, fake_run, monkeypatch
) -> None:
    fake_psql.default = ""
    fake_psql.on("tpl", returns="1\n")
    monkeypatch.setattr(
        "dbctl.modules.detect",
        lambda cfg: {
            "base_ref": "origin/main",
            "base_sha": "abc",
            "modules": ["demo"],
            "changed_paths": ["addons/demo/x.py"],
            "excluded": [],
            "unmatched": [],
        },
    )
    monkeypatch.setattr("dbctl.postgres.installed_modules", lambda c, db: set())
    result = create.run(make_config())
    assert result["upgrade"]["install"] == ["demo"]
    # schema applied BEFORE the final start
    run_idx = next(
        i for i, c in enumerate(fake_compose.calls) if "run" in c and "--stop-after-init" in c
    )
    up_idx = next(i for i, c in enumerate(fake_compose.calls) if "up" in c)
    assert run_idx < up_idx
